# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
SentenceCard.create(phrase: 'What is that smell?')
SentenceCard.create(phrase: 'What is that sound?')
SentenceCard.create(phrase: 'I drink to forget ____________ .')
SentenceCard.create(phrase: 'What ended my last relationship?')
SentenceCard.create(phrase: '_____________ that is how i want to die.')
SentenceCard.create(phrase: 'Instead of coal Santa now gives bad children _____________ .')
SentenceCard.create(phrase: '_____________ high five bro!')
SentenceCard.create(phrase: '_____________ its a trap!!!!')
SentenceCard.create(phrase: 'What gives me uncontrollable gas?')
SentenceCard.create(phrase: 'What do old people smell like?')
SentenceCard.create(phrase: 'When Pharoh remained unmoved, Moses called down a plague of _____________ .')
SentenceCard.create(phrase: 'What is my secret power?')
SentenceCard.create(phrase: 'In Michael Jacksons final moments, he thought about ____________ .')
SentenceCard.create(phrase: 'Why do I hurt all over?')
SentenceCard.create(phrase: 'In an attempt to reach a wider audience, the Smithosonian Museum of Natural History has opened an interactive exhibit on ____________ .')
SentenceCard.create(phrase: 'What is Batmans guilty pleasure?')

AnswerCard.create(phrase: 'Being a fricken awesome sorcer!!!')
AnswerCard.create(phrase: 'Dying')
AnswerCard.create(phrase: 'Roofies')
AnswerCard.create(phrase: 'The Big Bang')
AnswerCard.create(phrase: 'Morgan Freemans voice.')
AnswerCard.create(phrase: 'Taking off your shirt.')
AnswerCard.create(phrase: 'Nazis')
AnswerCard.create(phrase: 'Hormone injections')
AnswerCard.create(phrase: 'A Bop-IT')
AnswerCard.create(phrase: 'Obesity')
AnswerCard.create(phrase: 'Powerful thighs')
AnswerCard.create(phrase: 'Grandma')
AnswerCard.create(phrase: 'A monkey smoking a cigar.')
AnswerCard.create(phrase: 'Wearing underwear inside-out to avoid doing laundry.')
AnswerCard.create(phrase: 'Vigorous jazz hands')
AnswerCard.create(phrase: 'A cooler full of organs')
AnswerCard.create(phrase: 'Cheating in the special olympics')
AnswerCard.create(phrase: 'Homeless people')
AnswerCard.create(phrase: 'Home video of Oprah sobbing into a Lean Cuisine.')
AnswerCard.create(phrase: '72 virgins')
AnswerCard.create(phrase: 'A gassy antelope')
AnswerCard.create(phrase: 'BATMAN!!!!')
AnswerCard.create(phrase: 'A Mime having a stroke')
AnswerCard.create(phrase: 'A can of whoop-ass')
AnswerCard.create(phrase: 'A sassy black woman')
AnswerCard.create(phrase: 'Poorly timed Holocaust Jokes')
AnswerCard.create(phrase: 'fiery poops')
AnswerCard.create(phrase: 'Forgetting the Alamo')
AnswerCard.create(phrase: 'The Amish')
AnswerCard.create(phrase: 'Cock fights')
